USE [CCG]
GO

/****** Object:  Table [dbo].[TERMINALES_REGISTRADAS]    Script Date: 21/09/2019 3:12:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TERMINALES_REGISTRADAS](
	[IDTERMINAL] [int] IDENTITY(1,1) NOT NULL,
	[CODIGOUNICO] [int] NULL,
	[NIT] [bigint] NULL,
	[FECHAREGISTRO] [datetime] NULL,
	[City] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDTERMINAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TERMINALES_REGISTRADAS]  WITH CHECK ADD FOREIGN KEY([CODIGOUNICO])
REFERENCES [dbo].[MAESTRO_COMERCIOS] ([CODIGOUNICO])
GO

