USE [CCG]
GO

/****** Object:  Table [dbo].[MAESTRO_COMERCIOS]    Script Date: 21/09/2019 3:10:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MAESTRO_COMERCIOS](
	[CODIGOUNICO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRECOMERCIO] [varchar](255) NULL,
	[RAZONSOCIAL] [varchar](255) NULL,
	[NIT] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOUNICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

