USE [CCG]
GO

/****** Object:  Table [dbo].[NIT]    Script Date: 21/09/2019 3:11:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NIT](
	[IDNIT] [int] NULL,
	[DV] [varchar](255) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NIT]  WITH CHECK ADD FOREIGN KEY([IDNIT])
REFERENCES [dbo].[TERMINALES_REGISTRADAS] ([IDTERMINAL])
GO

