USE [CCG]
GO

/****** Object:  View [dbo].[viewnit]    Script Date: 21/09/2019 3:09:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[viewnit]
AS
SELECT        dbo.MAESTRO_COMERCIOS.CODIGOUNICO, dbo.MAESTRO_COMERCIOS.NOMBRECOMERCIO, dbo.MAESTRO_COMERCIOS.RAZONSOCIAL, dbo.TERMINALES_REGISTRADAS.IDTERMINAL, 
                         dbo.TERMINALES_REGISTRADAS.CODIGOUNICO AS tr, dbo.TERMINALES_REGISTRADAS.NIT, dbo.TERMINALES_REGISTRADAS.FECHAREGISTRO, dbo.NIT.IDNIT, dbo.NIT.DV
FROM            dbo.MAESTRO_COMERCIOS INNER JOIN
                         dbo.TERMINALES_REGISTRADAS ON dbo.MAESTRO_COMERCIOS.CODIGOUNICO = dbo.TERMINALES_REGISTRADAS.CODIGOUNICO INNER JOIN
                         dbo.NIT ON dbo.TERMINALES_REGISTRADAS.IDTERMINAL = dbo.NIT.IDNIT
GO

